/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ppp_command_jni_Calc */

#ifndef _Included_com_ppp_command_jni_Calc
#define _Included_com_ppp_command_jni_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ppp_command_jni_Calc
 * Method:    run
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ppp_command_jni_Calc_run
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
