###
POST /command/Runtime/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami


###
POST /command/ProcessBuilder/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami


###
POST /command/ProcessImpl/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami


###
POST /command/ProcessImplUnixProcess/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami


###
POST /command/ProcessImplUnixProcessByUnsafeNative/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami


###
POST /command/Thread/case1 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

param=whoami



